ai:
  default_response_instructions: |
    Return EITHER a generated JSON image (Creative and ImageAsset) if a creative prompt is provided OR GifSearchTags if not—never both. Example response: { "Text": "Your message here.", "Creative": "[IMG] A relevant visual description.", "ImageAsset": "https://image.pollinations.ai/prompt/{description}?width={width}&height={height}&seed={seed}&model=flux-realistic&nologo=true", "Hashtags": ["#Relevant", "#Contextual", "#GeneralTopic"] } or { "Text": "Message.", "Hashtags": ["#tag", "#tag", "#tag"], "GifSearchTags": ["term one", "term two", "term three"] }  Respond only with valid JSON. Do not write an introduction or summary.
  custom_system_instructions: |
    Return EITHER a generated JSON image (Creative and ImageAsset) if a creative prompt is provided OR GifSearchTags if not—never both.
  custom_user_instructions: 'Example response: { "Text": "Your message here.", "Creative": "[IMG] A relevant visual description.", "ImageAsset": "https://image.pollinations.ai/prompt/{description}?width={width}&height={height}&seed={seed}&model=flux-realistic&nologo=true", "Hashtags": ["#Relevant", "#Contextual", "#GeneralTopic"] } or { "Text": "Message.", "Hashtags": ["#tag", "#tag", "#tag"], "GifSearchTags": ["term one", "term two", "term three"] }'
  text:
    generate_text:
      enabled: true
      user_description: |
        If true, generates a tailored AI Social Media Post and An Image Or Gif
      prompt: Create a high-quality AI-generated image relevant to the blog content.
      LLM: Pollinations_Text_Advanced
  creative:
    generate_image:
      enabled: true
      user_description: |
        If true, generates a fallback image if the prompt fails to create one
      width: 1024
      height: 1024
      prompt: Create a high-quality AI-generated image relevant to the blog content.
      LLM: Pollinations_Image_Get
    fetch_gif:
      enabled: true
      user_description: |
        If true, ai suggests tags from giphy then pick the giph with the most relevant title
      prompt: return atleast 3 giphy search terms in the returned object in an array
    generate_video:
      enabled: false
      user_description: If true, includes a video in the LinkedIn post to boost engagement.
      prompt: Generate a video that highlights the key points of the blog post.
  viral_posting:
    include_viral_formatting:
      enabled: true
      description: Ensures AI-generated posts follow viral structures.
    attention_grabbing_intro:
      enabled: true
      description: First sentence must hook the reader to capture attention.
    emotional_storytelling:
      enabled: true
      description: Includes personal/emotional elements to increase relatability.
    extreme_statements:
      enabled: false
      description: Uses bold statements to spark engagement/debate (if enabled).
    relatable_experiences:
      enabled: true
      description: Ensures the post connects with the audience's daily struggles.
    actionable_takeaways:
      enabled: true
      description: Posts must offer practical insights or solutions for readers.
    data-backed_claims:
      enabled: true
      description: Uses real data & examples to establish credibility and trust.
