user_profile:
  medium_username: codingoni
  wix_url: null
  wordpress_url: null
  target_audience: Non Technical People Looking For Tech Thought Leadership
  professional_summary: |
    I'm a Software Engineer with a passion for creating innovative
    solutions and sharing my knowledge with the world. I'm always looking for new
    ways to improve my skills and help others do the same.
  resume_url: https://www.linkedin.com/in/your-linkedin-url
